version: '3.4'
networks:
  mysql:
    external: true
services:
  dm:
    image: golang:1.14
    volumes:
      - ../../cds:/cds
    command:
       /cds/docker/build/dm -f /cds/dm/cmd/sync/etc/dm.json
  galaxy:
    image: golang:1.14
    container_name: galaxy
    ports:
      - "8080:8080"
    volumes:
      - ../../cds:/cds
    working_dir: /cds/galaxy
    command:
      /cds/docker/build/galaxy -f /cds/galaxy/etc/galaxy-api.json
  rtu:
    image: golang:1.14
    volumes:
      - ../../cds:/cds
    command:
      /cds/docker/build/rtu -f /cds/rtu/conf.json
  nginx:
    image: nginx
    ports:
      - 3414:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../logs:/var/log/nginx
      - ./html:/usr/local/html
