version: '2.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/test.sql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysql" ,"-h", "mysql", "-P", "3306", "-u", "root", "-proot" , "-e", "SELECT 1"]
      interval: 2s
      timeout: 5s
      retries: 30
  etcd:
    image: bitnami/etcd:3.4.13
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    healthcheck:
      test: ["CMD", "etcdctl", "member", "list", '--endpoints="localhost:2379"']
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 2s
      timeout: 5s
      retries: 30
  ch-server-1:
      image: yandex/clickhouse-server
      volumes:
        - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
        - ./clickhouse/macros1.xml:/etc/clickhouse-server/config.d/macros.xml
      ports:
        - 8123:8123
        - 9000:9000
      environment:
        TZ: "Asia/Shanghai"
      depends_on:
        mysql:
          condition: service_healthy
        redis:
          condition: service_healthy
        etcd:
          condition: service_healthy
        zookeeper:
          condition: service_healthy
  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macros2.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8124:8123
      - 9001:9000
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      etcd:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macros3.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8125:8123
      - 9002:9000
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      etcd:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
  ch-server-4:
    image: yandex/clickhouse-server
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macros4.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8126:8123
      - 9003:9000
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      etcd:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
  mongo:
    image: zadki3l/mongodb-oplog
    ports:
    - 27017:27017
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 10s
      timeout: 5s
