version: '2.1'
networks:
  mysql:
    external: true
services:
  kafka:
    image: ches/kafka
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 2s
      timeout: 5s
      retries: 30
  kafka-connector:
    image: liliankasem/kafka-connect:1.1.0
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java
    healthcheck:
      test: [ "CMD", "nc", "-z", "kafka-connector", "8083" ]
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - ./mongo-kafka-1.2.0-all.jar:/usr/share/java/mongo-kafka-1.2.0-all.jar
    depends_on:
      kafka:
        condition: service_healthy
  canal-admin:
    image: canal/canal-admin
    ports:
      - 8089:8089
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://canal-admin:8089" ]
      interval: 30s
      timeout: 15s
      retries: 30
    restart: always
    volumes:
      - ./canal_admin_conf/canal-template.properties:/home/admin/canal-admin/conf/canal-template.properties
  canal-server:
    image: canal/canal-server
    restart: always
    depends_on:
      canal-admin:
        condition: service_healthy
    environment:
      canal.admin.user: admin
      canal.admin.port: 11110
      canal.admin.passwd: 4ACFE3202A5FF5CF467898FC58AAB1D615029441
      canal.admin.manager: canal-admin:8089